name: level
favicon: null
layout_spectrum: 0.24367248080670834
typography_spectrum: 0.4674091774504632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.41933887405321
  lightness: 0.5904717156663537
  saturation: 0.2779373871162534
  rhythmicContrast: 0.1246691937558353
purpose: []
