favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0.41933887405321
  lightness: 0.9820789
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 0.6290323
typography_spectrum: 0.8315412
layout_spectrum: 0.2436724808067083
analytics:
  twitter: null
  google: null
  facebook: null
name: level
